<?php
define("HOST","localhost");
define("USER","root");
define("PWD","");
define("DATABASE","pap2022joao");
define("HOME",1);
define("CLUBES",2);
define("JOGADORES",3);
define("JOGOS",4);
define("NOTICIAS",5);
?>
